create database mydemodb;
show databases;
use mydemodb;
show tables;
create table student(roll int, sname varchar(10), course varchar(10));
desc student;
insert into student values(101,'rahul', 'python');
select * from student; 
insert into student values(56,'aayush','java');
select roll, sname from student;
drop table student;
insert into student values(45,'ashish','c++');
insert into student values(45,'ashish','c++'),(27,'zach','html'),(89,'sahil', 'css');
insert into student(roll, sname, course) values(45,'ashish','c++');
update student set sname='brian' where sname='sahil';
insert into student values(29,'aayush','java');
select * from student where sname = 'aayush'; 
select * from student where roll = 29;
select * from student where roll = 29 and sname = 'aayush';
select * from student where roll = 29 or roll = 56;
select * from student order by roll;
select * from student order by roll desc;
select * from student where roll between 40 and 50;
insert into student values(46,'ashish','c++');
delete from student where roll = 46 and sname = 'ashish' and course = 'c++';
delete from student;
alter table student add column(location varchar(10));
alter table student drop column location;
select count(*) from student;	
select min(roll) from student;
select max(roll) from student;
select avg(roll) from student;
select sum(roll) from student;
select sname from student where sname like 'r%';
select sname from student where sname like 'ra%';
select sname from student where sname like '%h';
select sname from student where sname like '%u%';
select sname from student where sname like '__h%';
select * from student where roll < 50;
select * from student where roll >= 40 and roll <= 50;